### ISSUE TITLE
os.rename, FileExistsError: [WinError 183]

### ISSUE THREAD

**Issue by mitaa** [brainsik/json-store#18]
Seems to be broken for Windows right now.

https://docs.python.org/3/library/os.html#os.rename
"On Windows, if dst exists a [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) is always raised."

Apparently os.replace should be a good cross-platform fix, though I'm not sure about atomicity on Windows.
https://docs.python.org/3/library/os.html#os.replace

**Comment by brainsik** [comment]
Thanks for the report!

**Comment by brainsik** [comment]
I'll drop a comment when I cut a new release with this. Should be soon.

**Comment by brainsik** [comment]
json-store 4.0 is available on PyPI with these changes

**Comment by mitaa** [comment]
Thanks!
